version: '3.8'

services:
  db_pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: tulona
      POSTGRES_DB: postgresdb
      POSTGRES_PASSWORD: anolut
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  db_mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: corporate
      MYSQL_USER: tulona
      MYSQL_PASSWORD: anolut
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  default:
    name: tulona-net

volumes:
  postgres-data:
  mysql-data:
