name: tulona-3.8
channels:
  - conda-forge
  - defaults
dependencies:
  - click~=8.1
  - ruamel.yaml~=0.18
  - psycopg2-binary~=2.9
  - pymysql~=1.1
  - cryptography~=42.0
  - snowflake-sqlalchemy~=1.5
  - pyodbc~=5.1
  - pandas~=1.5 # can't upgrade until https://github.com/pandas-dev/pandas/issues/57053 is resolved
  - openpyxl~=3.1
  - Jinja2~=3.1
  - pytest~=8.1
  - flake8
  - coverage
  - black
  - isort
  - pytest-cov
  - faker
  - python=3.8.*