name: Linting
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4.7.0
      - uses: pre-commit/action@v3.0.0