name: Github Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test-publish:
    runs-on: ubuntu-latest
    environment: testpypi
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install setuptools wheel build
    - name: Build wheel & tarball
      run: |
        python -m build
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Github release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
        gh release create ${{ github.ref_name }}
        --generate-notes
        --title "tulona ${{ github.ref_name }}"