name: Tests

on: [pull_request]

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        exclude:
            - os: "windows-latest"
              python-version: "3.12"
            - os: "ubuntu-latest"
              python-version: "3.12"
            - os: "macos-latest"
              python-version: "3.12"

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      PARALLEL: "true"
      COVERAGE: "true"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed by codecov.io

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment-${{ matrix.python-version }}.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        shell: bash -l {0}
        run: source ci/scripts/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: source ci/scripts/run_tests.sh

      - name: Coverage
        uses: codecov/codecov-action@v4
